/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PanelRouteImport } from './routes/_panel'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PanelDashboardRouteImport } from './routes/_panel.dashboard'
import { Route as PanelNotificacionesRouteImport } from './routes/_panel.notificaciones'
import { Route as PanelPerfilRouteImport } from './routes/_panel.perfil'
import { Route as AuthCompleteRouteImport } from './routes/auth.complete'
import { Route as PanelTicketsIndexRouteImport } from './routes/_panel.tickets.index'
import { Route as PanelTicketsIdRouteImport } from './routes/_panel.tickets.$id'
import { Route as PanelTicketsNuevoRouteImport } from './routes/_panel.tickets.nuevo'
import { Route as ApiPublicAuthDiscordCallbackRouteImport } from './routes/api/public/auth/discord.callback'
import { Route as ApiPublicAuthDiscordStartRouteImport } from './routes/api/public/auth/discord.start'
import { Route as ApiPublicAuthRobloxCallbackRouteImport } from './routes/api/public/auth/roblox.callback'
import { Route as ApiPublicAuthRobloxStartRouteImport } from './routes/api/public/auth/roblox.start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/_panel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelDashboardRoute = PanelDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PanelRoute,
} as any)
const PanelNotificacionesRoute = PanelNotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => PanelRoute,
} as any)
const PanelPerfilRoute = PanelPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => PanelRoute,
} as any)
const AuthCompleteRoute = AuthCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => AuthRoute,
} as any)
const PanelTicketsIndexRoute = PanelTicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => PanelRoute,
} as any)
const PanelTicketsIdRoute = PanelTicketsIdRouteImport.update({
  id: '/tickets/$id',
  path: '/tickets/$id',
  getParentRoute: () => PanelRoute,
} as any)
const PanelTicketsNuevoRoute = PanelTicketsNuevoRouteImport.update({
  id: '/tickets/nuevo',
  path: '/tickets/nuevo',
  getParentRoute: () => PanelRoute,
} as any)
const ApiPublicAuthDiscordCallbackRoute =
  ApiPublicAuthDiscordCallbackRouteImport.update({
    id: '/api/public/auth/discord/callback',
    path: '/api/public/auth/discord/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthDiscordStartRoute =
  ApiPublicAuthDiscordStartRouteImport.update({
    id: '/api/public/auth/discord/start',
    path: '/api/public/auth/discord/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthRobloxCallbackRoute =
  ApiPublicAuthRobloxCallbackRouteImport.update({
    id: '/api/public/auth/roblox/callback',
    path: '/api/public/auth/roblox/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthRobloxStartRoute =
  ApiPublicAuthRobloxStartRouteImport.update({
    id: '/api/public/auth/roblox/start',
    path: '/api/public/auth/roblox/start',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof PanelDashboardRoute
  '/notificaciones': typeof PanelNotificacionesRoute
  '/perfil': typeof PanelPerfilRoute
  '/auth/complete': typeof AuthCompleteRoute
  '/tickets/$id': typeof PanelTicketsIdRoute
  '/tickets/nuevo': typeof PanelTicketsNuevoRoute
  '/tickets/': typeof PanelTicketsIndexRoute
  '/api/public/auth/discord/callback': typeof ApiPublicAuthDiscordCallbackRoute
  '/api/public/auth/discord/start': typeof ApiPublicAuthDiscordStartRoute
  '/api/public/auth/roblox/callback': typeof ApiPublicAuthRobloxCallbackRoute
  '/api/public/auth/roblox/start': typeof ApiPublicAuthRobloxStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof PanelDashboardRoute
  '/notificaciones': typeof PanelNotificacionesRoute
  '/perfil': typeof PanelPerfilRoute
  '/auth/complete': typeof AuthCompleteRoute
  '/tickets/$id': typeof PanelTicketsIdRoute
  '/tickets/nuevo': typeof PanelTicketsNuevoRoute
  '/tickets': typeof PanelTicketsIndexRoute
  '/api/public/auth/discord/callback': typeof ApiPublicAuthDiscordCallbackRoute
  '/api/public/auth/discord/start': typeof ApiPublicAuthDiscordStartRoute
  '/api/public/auth/roblox/callback': typeof ApiPublicAuthRobloxCallbackRoute
  '/api/public/auth/roblox/start': typeof ApiPublicAuthRobloxStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_panel': typeof PanelRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_panel/dashboard': typeof PanelDashboardRoute
  '/_panel/notificaciones': typeof PanelNotificacionesRoute
  '/_panel/perfil': typeof PanelPerfilRoute
  '/auth/complete': typeof AuthCompleteRoute
  '/_panel/tickets/$id': typeof PanelTicketsIdRoute
  '/_panel/tickets/nuevo': typeof PanelTicketsNuevoRoute
  '/_panel/tickets/': typeof PanelTicketsIndexRoute
  '/api/public/auth/discord/callback': typeof ApiPublicAuthDiscordCallbackRoute
  '/api/public/auth/discord/start': typeof ApiPublicAuthDiscordStartRoute
  '/api/public/auth/roblox/callback': typeof ApiPublicAuthRobloxCallbackRoute
  '/api/public/auth/roblox/start': typeof ApiPublicAuthRobloxStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/notificaciones'
    | '/perfil'
    | '/auth/complete'
    | '/tickets/$id'
    | '/tickets/nuevo'
    | '/tickets/'
    | '/api/public/auth/discord/callback'
    | '/api/public/auth/discord/start'
    | '/api/public/auth/roblox/callback'
    | '/api/public/auth/roblox/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/notificaciones'
    | '/perfil'
    | '/auth/complete'
    | '/tickets/$id'
    | '/tickets/nuevo'
    | '/tickets'
    | '/api/public/auth/discord/callback'
    | '/api/public/auth/discord/start'
    | '/api/public/auth/roblox/callback'
    | '/api/public/auth/roblox/start'
  id:
    | '__root__'
    | '/'
    | '/_panel'
    | '/auth'
    | '/_panel/dashboard'
    | '/_panel/notificaciones'
    | '/_panel/perfil'
    | '/auth/complete'
    | '/_panel/tickets/$id'
    | '/_panel/tickets/nuevo'
    | '/_panel/tickets/'
    | '/api/public/auth/discord/callback'
    | '/api/public/auth/discord/start'
    | '/api/public/auth/roblox/callback'
    | '/api/public/auth/roblox/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PanelRoute: typeof PanelRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiPublicAuthDiscordCallbackRoute: typeof ApiPublicAuthDiscordCallbackRoute
  ApiPublicAuthDiscordStartRoute: typeof ApiPublicAuthDiscordStartRoute
  ApiPublicAuthRobloxCallbackRoute: typeof ApiPublicAuthRobloxCallbackRoute
  ApiPublicAuthRobloxStartRoute: typeof ApiPublicAuthRobloxStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_panel': {
      id: '/_panel'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_panel/dashboard': {
      id: '/_panel/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PanelDashboardRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/notificaciones': {
      id: '/_panel/notificaciones'
      path: '/notificaciones'
      fullPath: '/notificaciones'
      preLoaderRoute: typeof PanelNotificacionesRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/perfil': {
      id: '/_panel/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PanelPerfilRouteImport
      parentRoute: typeof PanelRoute
    }
    '/auth/complete': {
      id: '/auth/complete'
      path: '/complete'
      fullPath: '/auth/complete'
      preLoaderRoute: typeof AuthCompleteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_panel/tickets/': {
      id: '/_panel/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof PanelTicketsIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/tickets/$id': {
      id: '/_panel/tickets/$id'
      path: '/tickets/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof PanelTicketsIdRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/tickets/nuevo': {
      id: '/_panel/tickets/nuevo'
      path: '/tickets/nuevo'
      fullPath: '/tickets/nuevo'
      preLoaderRoute: typeof PanelTicketsNuevoRouteImport
      parentRoute: typeof PanelRoute
    }
    '/api/public/auth/discord/callback': {
      id: '/api/public/auth/discord/callback'
      path: '/api/public/auth/discord/callback'
      fullPath: '/api/public/auth/discord/callback'
      preLoaderRoute: typeof ApiPublicAuthDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/discord/start': {
      id: '/api/public/auth/discord/start'
      path: '/api/public/auth/discord/start'
      fullPath: '/api/public/auth/discord/start'
      preLoaderRoute: typeof ApiPublicAuthDiscordStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/roblox/callback': {
      id: '/api/public/auth/roblox/callback'
      path: '/api/public/auth/roblox/callback'
      fullPath: '/api/public/auth/roblox/callback'
      preLoaderRoute: typeof ApiPublicAuthRobloxCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/roblox/start': {
      id: '/api/public/auth/roblox/start'
      path: '/api/public/auth/roblox/start'
      fullPath: '/api/public/auth/roblox/start'
      preLoaderRoute: typeof ApiPublicAuthRobloxStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PanelRouteChildren {
  PanelDashboardRoute: typeof PanelDashboardRoute
  PanelNotificacionesRoute: typeof PanelNotificacionesRoute
  PanelPerfilRoute: typeof PanelPerfilRoute
  PanelTicketsIdRoute: typeof PanelTicketsIdRoute
  PanelTicketsNuevoRoute: typeof PanelTicketsNuevoRoute
  PanelTicketsIndexRoute: typeof PanelTicketsIndexRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelDashboardRoute: PanelDashboardRoute,
  PanelNotificacionesRoute: PanelNotificacionesRoute,
  PanelPerfilRoute: PanelPerfilRoute,
  PanelTicketsIdRoute: PanelTicketsIdRoute,
  PanelTicketsNuevoRoute: PanelTicketsNuevoRoute,
  PanelTicketsIndexRoute: PanelTicketsIndexRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

interface AuthRouteChildren {
  AuthCompleteRoute: typeof AuthCompleteRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCompleteRoute: AuthCompleteRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PanelRoute: PanelRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiPublicAuthDiscordCallbackRoute: ApiPublicAuthDiscordCallbackRoute,
  ApiPublicAuthDiscordStartRoute: ApiPublicAuthDiscordStartRoute,
  ApiPublicAuthRobloxCallbackRoute: ApiPublicAuthRobloxCallbackRoute,
  ApiPublicAuthRobloxStartRoute: ApiPublicAuthRobloxStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
